version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgis/postgis
    ports:
      - target: 5432
        published: 5432
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    env_file: ./.env
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  pgdata:
    driver: local
